name: parse_the_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - -e .
      - structlog>=24.1
      - pydantic>=2.6
      - black>=24.4
      - isort>=5.13
      - ruff>=0.4.4
      - pytest>=8.2
      - mcp
      - PyPDF2
      - python-docx
      - numpy
      - pandas
      - json
